name: Package
on:
  push:
    branches: [ master ]
jobs:
  package-root-rampage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Install gdown
        run: pip install gdown

      - name: Checkout
        uses: actions/checkout@v3

      - name: Download assets
        run: cd $GITHUB_WORKSPACE && gdown --folder "1euQ8-cIlN86nV4YCi8xXbShAeMtl_XTr"

      - name: Create packages
        uses: nhartland/love-build@master
        id: love-build
        with:
          app_name: 'root_rampage'
          love_version: '11.4'
      - uses: actions/upload-artifact@v4
        with:
          name: hw_macos-build
          path: ${{ steps.love-build.outputs.macos-filename }}
      - uses: actions/upload-artifact@v4
        with:
          name: hw_win32-build
          path: ${{ steps.love-build.outputs.win32-filename }}
      - uses: actions/upload-artifact@v4
        with:
          name: hw_win64-build
          path: ${{ steps.love-build.outputs.win64-filename }}
      - uses: actions/upload-artifact@v4
        with:
          name: hw_love-build
          path: ${{ steps.love-build.outputs.love-filename }}