name: Package
on:
  push:
    branches: [ master ]
jobs:
  package-root-rampage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-python@v5
        with:
          python-version: '3.9'
          cache: 'pip'

      - name: Install gdown
        run: pip install gdown

      - name: Download assets
        run: gdown --folder "1JssgVA4UbAUl7g3SLxaTNbpIBH0zegPj

      - uses: actions/checkout@v3
      - uses: nhartland/love-build@master
        id: love-build
        with:
          app_name: 'root_rampage'
          love_version: '11.4'
      - uses: actions/upload-artifact@v1
        with:
          name: hw_macos-build
          path: ${{ steps.love-build.outputs.macos-filename }}
      - uses: actions/upload-artifact@v1
        with:
          name: hw_win32-build
          path: ${{ steps.love-build.outputs.win32-filename }}
      - uses: actions/upload-artifact@v1
        with:
          name: hw_win64-build
          path: ${{ steps.love-build.outputs.win64-filename }}
      - uses: actions/upload-artifact@v1
        with:
          name: hw_love-build
          path: ${{ steps.love-build.outputs.love-filename }}